TARGET = libmsiobjput_mdbam.so

SRCS = libmsiobjput_mdbam.cpp

EXTRALIBS = /root/workspace/samtools/libbam.a /root/workspace/htslib/libhts.a

include ../Makefile.base

INC += -I/root/workspace/samtools -I/root/workspace/htslib
